version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_container
    ports:
      - "80:80"
    volumes:
      - ${PWD}/../models:/app
      - .:/app
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_container
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge